name: stickereditor
description: A widget that lets you modify and move your text and image according to your boundaries.
version: 0.0.5
homepage: https://github.com/Harsh-Radadiya/sticker_editor/blob/master/example/lib/main.dart
repository: https://github.com/Harsh-Radadiya/sticker_editor

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"


dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.8
  dotted_border: ^2.0.0+1
  screenshot: ^1.2.3
  path_provider: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.stickereditor.stickereditor
        pluginClass: StickereditorPlugin
      ios:
        pluginClass: StickereditorPlugin
      macos:
        pluginClass: StickereditorPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/
    # - assets/Stickers/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
